# Домашнее задание.

Вам нужно решить задачи, предложенные в блокноте и отправить этот блокнот обратно через проект в ЛМС. 

Засчитываются только те задания, которые полностью выполнены и код работает (мы будем вручную запускать эти ячейки, поэтому если ваш код не сработает, то мы будем считать, что задание не выполненно).

Если мы обнаружим списанные работы - мы обнулим результат всем студентам, которых мы подозреваем в списывании. Если у нас будут сомнения, будет проведена защита домашнего задания по результатам которого, к домашнему заданию может быть применен штраф от 25 до 100%.




**Задание 1.**  
*5 баллов*  

1. На странице в https://en.wikipedia.org/wiki/Northwest_Airlines#Incidents_and_accidents нужно найти таблицу под названием "Northwest Airlines Reported Incidents". 

2. С помощью поиска по тегам, нужно сохранить из таблицы следующие колонки: 'Date', 'Aircraft', 'Casualties (Fatal)'. Каждая колонка таблицы должна быть сохранена в отдельную переменную (см. ниже названия), внутри которой лежит список, где первое значение - название колонки. 

Обатите внимание, что во втором ряде таблицы после скрэйпинга будут лежать подзаголовки колонки Casualties. Учитывайте, что при работе с таблицей вам нужно будет его пропустить.

Так же обратите внимание, что внизу таблицы есть два ряда total, информацию из них сохранять не нужно.

Например, для колонки 'Aircraft' список будет выглядеть так:  
['Aircraft', "Lockheed Model 14", ...остальные значения..., 	"Boeing 727"]

3. Выведите эти три списка командой  
print(dates)  
print(aircrafts)  
print(casualties)

*Правильный ответ*  
`['Date', 'January 10, 1938', 'October 30, 1941', 'March 12, 1948', 'August 29, 1948', 'October 27, 1948', 'March 7, 1950', 'June 23, 1950', 'October 13, 1950', 'November 7, 1950', 'January 16, 1951', 'January 19, 1952', 'April 2, 1956', 'March 17, 1960', 'July 14, 1960', 'October 28, 1960', 'September 16, 1961', 'February 12, 1963', 'June 3, 1963', 'December 1, 1974', 'January 20, 1983', 'August 16, 1987', 'December 3, 1990', 'December 3, 1990']`

`['Aircraft', 'LockheedModel 14', 'Douglas DC-3', 'Douglas DC-4', 'Martin 202', 'Douglas DC-4', 'Martin 202', 'Douglas DC-4', 'Martin 202', 'Martin 202', 'Martin 202', 'Douglas C-54', 'Boeing Stratocruiser', 'Lockheed L-188 Electra', 'Douglas DC-7', 'Douglas C-54', 'Lockheed L-188 Electra', 'Boeing 720', 'Douglas DC-7', 'Boeing 727', 'Boeing 727', 'McDonnell-Douglas MD-82', 'Douglas DC-9', 'Boeing 727']`

`['Casualties', '10', '14', '30', '37', '2', '13', '58', '6', '21', '10', '36', '5', '63', '1', '12', '37', '43', '101', '3', '1', '154', '8', '']`


In [53]:
# Ваше решение. При необходимости создавайте новые ячейки под этой с помощью знака +
from bs4 import BeautifulSoup
import requests


url = 'https://en.wikipedia.org/wiki/Northwest_Airlines#Incidents_and_accidents'


soup = BeautifulSoup(requests.get(url).text,'html.parser')
table = soup.find(class_='toccolours')


rows = table.find_all('tr')

dates = [rows[0].find_all('th')[1].get_text().strip()]

for row in rows[2:-2]:
    dates.append(row.find_all('td')[1].get_text().strip())

aircrafts = [rows[0].find_all('th')[2].get_text().strip()]

for row in rows[2:-2]:
    aircrafts.append(row.find_all('td')[2].get_text().strip())

casualties = [rows[0].find_all('th')[5].get_text().strip()]

for row in rows[2:-2]:
    casualties.append(row.find_all('td')[5].get_text().strip())

print(dates)
print(aircrafts)
print(casualties)


['Date', 'January 10, 1938', 'October 30, 1941', 'March 12, 1948', 'August 29, 1948', 'October 27, 1948', 'March 7, 1950', 'June 23, 1950', 'October 13, 1950', 'November 7, 1950', 'January 16, 1951', 'January 19, 1952', 'April 2, 1956', 'March 17, 1960', 'July 14, 1960', 'October 28, 1960', 'September 16, 1961', 'February 12, 1963', 'June 3, 1963', 'December 1, 1974', 'January 20, 1983', 'August 16, 1987', 'December 3, 1990', 'December 3, 1990']
['Aircraft', 'LockheedModel 14', 'Douglas DC-3', 'Douglas DC-4', 'Martin 202', 'Douglas DC-4', 'Martin 202', 'Douglas DC-4', 'Martin 202', 'Martin 202', 'Martin 202', 'Douglas C-54', 'Boeing Stratocruiser', 'Lockheed L-188 Electra', 'Douglas DC-7', 'Douglas C-54', 'Lockheed L-188 Electra', 'Boeing 720', 'Douglas DC-7', 'Boeing 727', 'Boeing 727', 'McDonnell-Douglas MD-82', 'Douglas DC-9', 'Boeing 727']
['Casualties', '10', '14', '30', '37', '2', '13', '58', '6', '21', '10', '36', '5', '63', '1', '12', '37', '43', '101', '3', '1', '154', '8', ''

**Задание 2.**  
*5 баллов (каждый шаг 1 балл)*  
В задании вы должны использовать данные, собранные в пункте 1. Задание, выполненное без использования автоматически собранных данных, не засчитывается (например, если вы скопировали все значения из таблицы вручную и нашли их среднее).

1. В вашем списке casualties есть одно пропущенное значение (''). Напишите программу, которая находит в списке индекс этого элемента и заменяет его значение на 0. Переведите все значения кроме первого в этом списке в формат int.
Правильный список будет выглядеть так: `['Casualties', 10, 14, 30, 37, 2, 13, 58, 6, 21, 10, 36, 5, 63, 1, 12, 37, 43, 101, 3, 1, 154, 8, 0]`

2. Создайте словарь disasters, в котором ключ - дата крушения, а значение - список из названия самолета и количества погибших.
Словарь будет выглядеть так: `{'January 10, 1938': ['LockheedModel 14', 10], 'October 30, 1941': ['Douglas DC-3', 14], 'March 12, 1948': ['Douglas DC-4', 30], 'August 29, 1948': ['Martin 202', 37], 'October 27, 1948': ['Douglas DC-4', 2], 'March 7, 1950': ['Martin 202', 13], 'June 23, 1950': ['Douglas DC-4', 58], 'October 13, 1950': ['Martin 202', 6], 'November 7, 1950': ['Martin 202', 21], 'January 16, 1951': ['Martin 202', 10], 'January 19, 1952': ['Douglas C-54', 36], 'April 2, 1956': ['Boeing Stratocruiser', 5], 'March 17, 1960': ['Lockheed L-188 Electra', 63], 'July 14, 1960': ['Douglas DC-7', 1], 'October 28, 1960': ['Douglas C-54', 12], 'September 16, 1961': ['Lockheed L-188 Electra', 37], 'February 12, 1963': ['Boeing 720', 43], 'June 3, 1963': ['Douglas DC-7', 101], 'December 1, 1974': ['Boeing 727', 3], 'January 20, 1983': ['Boeing 727', 1], 'August 16, 1987': ['McDonnell-Douglas MD-82', 154], 'December 3, 1990': ['Boeing 727', 0]}`

3. Напишите функцию, которая берет аргументом дату и печатает следующую строку: Northwest Airlines {название самолета} crushed on {дата крушения} with total{количество погибших} fatal casualties

4. Запустите вашу функцию в цикле для всех дат.

5. Напишите программу, которая находит индекс наименьшего значения погибших в списке casualties. Выведите модель самолета, которая потерпела крушение в этом рейсе.

In [37]:
# обработка списка casualties

for i in range(len(casualties)):
    if casualties[i] == '':
        casualties[i] = 0
    else:
        if i != 0:
            casualties[i] = int(casualties[i])

print(casualties)

['Casualties', 10, 14, 30, 37, 2, 13, 58, 6, 21, 10, 36, 5, 63, 1, 12, 37, 43, 101, 3, 1, 154, 8, 0]


In [38]:
# словарь

disasters = {}
for i in range(1, len(dates)):
    disasters[dates[i]] = [aircrafts[i], casualties[i]]

print(disasters)

{'January 10, 1938': ['LockheedModel 14', 10], 'October 30, 1941': ['Douglas DC-3', 14], 'March 12, 1948': ['Douglas DC-4', 30], 'August 29, 1948': ['Martin 202', 37], 'October 27, 1948': ['Douglas DC-4', 2], 'March 7, 1950': ['Martin 202', 13], 'June 23, 1950': ['Douglas DC-4', 58], 'October 13, 1950': ['Martin 202', 6], 'November 7, 1950': ['Martin 202', 21], 'January 16, 1951': ['Martin 202', 10], 'January 19, 1952': ['Douglas C-54', 36], 'April 2, 1956': ['Boeing Stratocruiser', 5], 'March 17, 1960': ['Lockheed L-188 Electra', 63], 'July 14, 1960': ['Douglas DC-7', 1], 'October 28, 1960': ['Douglas C-54', 12], 'September 16, 1961': ['Lockheed L-188 Electra', 37], 'February 12, 1963': ['Boeing 720', 43], 'June 3, 1963': ['Douglas DC-7', 101], 'December 1, 1974': ['Boeing 727', 3], 'January 20, 1983': ['Boeing 727', 1], 'August 16, 1987': ['McDonnell-Douglas MD-82', 154], 'December 3, 1990': ['Boeing 727', 0]}


In [39]:
# функция

def information_by_the_date(date):
    needed_aircraft = disasters[date][0]
    needed_casualties = disasters[date][1]
    print("Northwest Airlines", needed_aircraft, "crushed on", date, "with total", needed_casualties, "fatal casualties")

Northwest Airlines LockheedModel 14 crushed on January 10, 1938 with total 10 fatal casualties
None


In [40]:
# функция в цикле

for date in disasters:
    information_by_the_date(date)

Northwest Airlines LockheedModel 14 crushed on January 10, 1938 with total 10 fatal casualties
Northwest Airlines Douglas DC-3 crushed on October 30, 1941 with total 14 fatal casualties
Northwest Airlines Douglas DC-4 crushed on March 12, 1948 with total 30 fatal casualties
Northwest Airlines Martin 202 crushed on August 29, 1948 with total 37 fatal casualties
Northwest Airlines Douglas DC-4 crushed on October 27, 1948 with total 2 fatal casualties
Northwest Airlines Martin 202 crushed on March 7, 1950 with total 13 fatal casualties
Northwest Airlines Douglas DC-4 crushed on June 23, 1950 with total 58 fatal casualties
Northwest Airlines Martin 202 crushed on October 13, 1950 with total 6 fatal casualties
Northwest Airlines Martin 202 crushed on November 7, 1950 with total 21 fatal casualties
Northwest Airlines Martin 202 crushed on January 16, 1951 with total 10 fatal casualties
Northwest Airlines Douglas C-54 crushed on January 19, 1952 with total 36 fatal casualties
Northwest Airlin

In [54]:
# наименьшее количество жертв

for i in range(1, len(casualties)):
    if casualties[i] == min(casualties[1:]):
        print(aircrafts[i])

Boeing 727
